---
name: rotoscope

env:
  ROTOSCOPE_COMPILE_ERROR: '1'

up:
  - ruby: 2.4.3
  - homebrew:
    - clang-format
  - bundler

commands:
  build: bundle exec rake build
  test: bundle exec rake test
  fmt: bin/fmt
